import type { CatalogItem, Credential, Environment, Pod, Team } from "./types";

export const teams: Team[] = [
  { id: "team-studio1", name: "studio1-team" },
  { id: "team-studio2", name: "studio2-team" },
  { id: "team-data-platform", name: "data-platform" },
  { id: "team-sre", name: "sre" },
];

export const catalogItems: CatalogItem[] = [
  {
    id: "cat-vertica",
    name: "Vertica",
    tenancy: "multi",
    transport: "streamable-http",
    command: "node",
    args: ["/path/to/server.js", "--verbose"],
    image:
      "europe-west1-docker.pkg.dev/friendly-path-465518-r6/archestra-public/mcp-alchemy:latest",
    httpPort: 8080,
    httpPath: "/mcp",
    authType: "none",
    labels: ["demo:playtika"],
    fields: [
      {
        key: "host",
        kind: "env",
        type: "string",
        required: true,
        description: "Vertica host",
      },
      {
        key: "port",
        kind: "env",
        type: "number",
        required: true,
        description: "Vertica port",
      },
      {
        key: "database",
        kind: "env",
        type: "string",
        required: true,
        description: "Database name (set per environment)",
      },
      {
        key: "dialect",
        kind: "env",
        type: "string",
        required: true,
        description: "DB dialect package",
        staticValue: "psycopg2-binary",
      },
      {
        key: "username",
        kind: "user",
        type: "string",
        required: true,
        source: "prompt-install",
        description: "DB user",
      },
      {
        key: "password",
        kind: "user",
        type: "secret",
        required: true,
        source: "prompt-install",
        description: "DB password",
      },
    ],
    mappings: [
      {
        source: { kind: "field", key: "dialect" },
        target: { kind: "env-var", name: "DB_DIALECT_PACKAGE" },
      },
      {
        source: { kind: "field", key: "database" },
        target: { kind: "env-var", name: "STUDIO" },
      },
      {
        source: {
          kind: "template",
          template:
            "postgresql+{env.dialect}://{user.username}:{user.password}@{env.host}:{env.port}/{env.database}",
        },
        target: { kind: "header", name: "x-db-url" },
      },
    ],
  },
  {
    id: "cat-context7",
    name: "context7",
    tenancy: "single",
    transport: "stdio",
    command: undefined,
    args: ["-y", "@upstash/context7-mcp"],
    authType: "token",
    labels: [],
    fields: [
      {
        key: "context7_api_key",
        kind: "user",
        type: "secret",
        required: true,
        source: "prompt-install",
        description:
          "Context7 API Key: The API key for the Context7 MCP server",
      },
    ],
    mappings: [
      {
        source: { kind: "field", key: "context7_api_key" },
        target: { kind: "env-var", name: "CONTEXT7_API_KEY" },
      },
    ],
  },
  {
    id: "cat-github",
    name: "GitHub",
    tenancy: "multi",
    transport: "streamable-http",
    command: "node",
    args: ["/server.js"],
    image: "ghcr.io/github/github-mcp:latest",
    httpPort: 8080,
    httpPath: "/mcp",
    authType: "token",
    labels: ["external"],
    fields: [
      {
        key: "api_base",
        kind: "env",
        type: "string",
        required: true,
        description: "GitHub API base URL",
      },
      {
        key: "scopes",
        kind: "env",
        type: "string",
        required: false,
        description: "Comma-separated OAuth scopes",
      },
      {
        key: "token",
        kind: "user",
        type: "secret",
        required: true,
        source: "header-per-call",
        description: "Personal access token",
      },
    ],
    mappings: [
      {
        source: { kind: "field", key: "api_base" },
        target: { kind: "env-var", name: "GH_API_BASE" },
      },
      {
        source: {
          kind: "template",
          template: "Bearer {user.token}",
        },
        target: { kind: "header", name: "Authorization" },
      },
    ],
  },
  {
    id: "cat-jira",
    name: "Jira",
    tenancy: "multi",
    transport: "stdio",
    command: "npx",
    args: ["-y", "mcp-atlassian"],
    authType: "token",
    labels: ["external"],
    fields: [
      {
        key: "jira_url",
        kind: "env",
        type: "string",
        required: true,
        description: "Jira base URL (e.g. https://acme.atlassian.net)",
      },
      {
        key: "projects_filter",
        kind: "env",
        type: "string",
        required: false,
        description: "Comma-separated project keys this env may access",
      },
      {
        key: "read_only",
        kind: "env",
        type: "bool",
        required: true,
        description: "If true, server exposes only read tools",
      },
      {
        key: "username",
        kind: "user",
        type: "string",
        required: true,
        source: "prompt-install",
        description: "Atlassian account email",
      },
      {
        key: "api_token",
        kind: "user",
        type: "secret",
        required: true,
        source: "prompt-install",
        description: "Jira API token (id.atlassian.com/manage-profile/security/api-tokens)",
      },
    ],
    mappings: [
      {
        source: { kind: "field", key: "jira_url" },
        target: { kind: "env-var", name: "JIRA_URL" },
      },
      {
        source: { kind: "field", key: "projects_filter" },
        target: { kind: "env-var", name: "JIRA_PROJECTS_FILTER" },
      },
      {
        source: { kind: "field", key: "read_only" },
        target: { kind: "env-var", name: "JIRA_READ_ONLY" },
      },
      {
        source: { kind: "field", key: "username" },
        target: { kind: "env-var", name: "JIRA_USERNAME" },
      },
      {
        source: { kind: "field", key: "api_token" },
        target: { kind: "env-var", name: "JIRA_API_TOKEN" },
      },
    ],
  },
];

export const environments: Environment[] = [
  {
    id: "env-vertica-studio1",
    catalogId: "cat-vertica",
    label: "Studio 1",
    visibility: {
      kind: "team",
      teamId: "team-studio1",
      teamName: "studio1-team",
    },
    fieldValues: {
      host: "postgresql.archestra-dev.svc.cluster.local",
      port: 5432,
      database: "studio1",
    },
    isDefault: false,
    createdAt: "2026-04-12T10:00:00Z",
  },
  {
    id: "env-vertica-studio2",
    catalogId: "cat-vertica",
    label: "Studio 2",
    visibility: {
      kind: "team",
      teamId: "team-studio2",
      teamName: "studio2-team",
    },
    fieldValues: {
      host: "postgresql.archestra-dev.svc.cluster.local",
      port: 5432,
      database: "studio2",
    },
    isDefault: false,
    createdAt: "2026-04-12T10:05:00Z",
  },
  {
    id: "env-context7-default",
    catalogId: "cat-context7",
    label: "default",
    visibility: { kind: "org" },
    fieldValues: {},
    isDefault: true,
    createdAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "env-github-readonly",
    catalogId: "cat-github",
    label: "prod-readonly",
    visibility: {
      kind: "team",
      teamId: "team-data-platform",
      teamName: "data-platform",
    },
    fieldValues: {
      api_base: "https://api.github.com",
      scopes: "repo:read,issues:read",
    },
    isDefault: false,
    createdAt: "2026-04-20T12:00:00Z",
  },
  {
    id: "env-github-admin",
    catalogId: "cat-github",
    label: "prod-admin",
    visibility: { kind: "team", teamId: "team-sre", teamName: "sre" },
    fieldValues: {
      api_base: "https://api.github.com",
      scopes: "repo,workflow,admin:org",
    },
    isDefault: false,
    createdAt: "2026-04-20T12:05:00Z",
  },
  {
    id: "env-jira-dev",
    catalogId: "cat-jira",
    label: "dev",
    visibility: { kind: "org" },
    fieldValues: {
      jira_url: "https://acme-dev.atlassian.net",
      projects_filter: "DEV,SANDBOX",
      read_only: false,
    },
    isDefault: true,
    createdAt: "2026-04-22T09:00:00Z",
  },
  {
    id: "env-jira-staging",
    catalogId: "cat-jira",
    label: "staging",
    visibility: {
      kind: "team",
      teamId: "team-data-platform",
      teamName: "data-platform",
    },
    fieldValues: {
      jira_url: "https://acme-staging.atlassian.net",
      projects_filter: "STG,DATA",
      read_only: false,
    },
    isDefault: false,
    createdAt: "2026-04-22T09:05:00Z",
  },
  {
    id: "env-jira-production",
    catalogId: "cat-jira",
    label: "production",
    visibility: { kind: "team", teamId: "team-sre", teamName: "sre" },
    fieldValues: {
      jira_url: "https://acme.atlassian.net",
      projects_filter: "OPS,INC,SEC",
      read_only: true,
    },
    isDefault: false,
    createdAt: "2026-04-22T09:10:00Z",
  },
];

export const pods: Pod[] = [
  {
    id: "pod-vertica-studio1-shared",
    name: "mcp-mt-2369-vertica",
    catalogId: "cat-vertica",
    environmentId: "env-vertica-studio1",
    ownerLabel: "shared",
    tenancy: "multi",
    status: "up",
    startedAt: "2026-05-03T22:35:00Z",
    restarts: 0,
    image: "europe-west1-docker.pkg.dev/.../mcp-alchemy:latest",
    callerCount: 2,
  },
  {
    id: "pod-vertica-studio2-shared",
    name: "mcp-mt-7a4c-vertica",
    catalogId: "cat-vertica",
    environmentId: "env-vertica-studio2",
    ownerLabel: "shared",
    tenancy: "multi",
    status: "up",
    startedAt: "2026-05-03T22:38:00Z",
    restarts: 0,
    image: "europe-west1-docker.pkg.dev/.../mcp-alchemy:latest",
    callerCount: 1,
  },
  {
    id: "pod-context7-admin",
    name: "mcp-context7-admin",
    catalogId: "cat-context7",
    environmentId: "env-context7-default",
    ownerLabel: "admin@example.com",
    tenancy: "single",
    status: "up",
    startedAt: "2026-05-02T14:00:00Z",
    restarts: 0,
    image: "node:20-alpine",
    callerCount: 1,
  },
  {
    id: "pod-context7-alice",
    name: "mcp-context7-alice",
    catalogId: "cat-context7",
    environmentId: "env-context7-default",
    ownerLabel: "alice@example.com",
    tenancy: "single",
    status: "up",
    startedAt: "2026-05-02T14:30:00Z",
    restarts: 0,
    image: "node:20-alpine",
    callerCount: 1,
  },
  {
    id: "pod-context7-bob",
    name: "mcp-context7-bob",
    catalogId: "cat-context7",
    environmentId: "env-context7-default",
    ownerLabel: "bob@example.com",
    tenancy: "single",
    status: "restarting",
    startedAt: "2026-05-03T23:01:00Z",
    restarts: 3,
    image: "node:20-alpine",
    callerCount: 1,
  },
  {
    id: "pod-github-readonly",
    name: "mcp-mt-3f2a-github",
    catalogId: "cat-github",
    environmentId: "env-github-readonly",
    ownerLabel: "shared",
    tenancy: "multi",
    status: "up",
    startedAt: "2026-04-25T09:00:00Z",
    restarts: 1,
    image: "ghcr.io/github/github-mcp:latest",
    callerCount: 5,
  },
  {
    id: "pod-github-admin",
    name: "mcp-mt-9b1e-github",
    catalogId: "cat-github",
    environmentId: "env-github-admin",
    ownerLabel: "shared",
    tenancy: "multi",
    status: "degraded",
    startedAt: "2026-04-25T09:05:00Z",
    restarts: 4,
    image: "ghcr.io/github/github-mcp:latest",
    callerCount: 2,
  },
  {
    id: "pod-jira-dev",
    name: "mcp-mt-1d2c-jira",
    catalogId: "cat-jira",
    environmentId: "env-jira-dev",
    ownerLabel: "shared",
    tenancy: "multi",
    status: "up",
    startedAt: "2026-04-22T09:00:00Z",
    restarts: 0,
    image: "node:20-alpine",
    callerCount: 4,
  },
  {
    id: "pod-jira-staging",
    name: "mcp-mt-5e8a-jira",
    catalogId: "cat-jira",
    environmentId: "env-jira-staging",
    ownerLabel: "shared",
    tenancy: "multi",
    status: "up",
    startedAt: "2026-04-22T09:05:00Z",
    restarts: 0,
    image: "node:20-alpine",
    callerCount: 2,
  },
  {
    id: "pod-jira-production",
    name: "mcp-mt-bf03-jira",
    catalogId: "cat-jira",
    environmentId: "env-jira-production",
    ownerLabel: "shared",
    tenancy: "multi",
    status: "up",
    startedAt: "2026-04-22T09:10:00Z",
    restarts: 1,
    image: "node:20-alpine",
    callerCount: 1,
  },
];

export const credentials: Credential[] = [
  {
    id: "cred-1",
    environmentId: "env-vertica-studio1",
    ownerId: "u-admin",
    ownerEmail: "admin@example.com",
    scope: "personal",
    podId: "pod-vertica-studio1-shared",
    secretStorage: "Database",
    createdAt: "2026-05-03T22:35:00Z",
  },
  {
    id: "cred-2",
    environmentId: "env-vertica-studio1",
    ownerId: "u-alice",
    ownerEmail: "alice@example.com",
    scope: "personal",
    podId: "pod-vertica-studio1-shared",
    secretStorage: "Database",
    createdAt: "2026-05-03T22:40:00Z",
  },
  {
    id: "cred-3",
    environmentId: "env-vertica-studio2",
    ownerId: "u-bob",
    ownerEmail: "bob@example.com",
    scope: "personal",
    podId: "pod-vertica-studio2-shared",
    secretStorage: "Database",
    createdAt: "2026-05-03T22:42:00Z",
  },
  {
    id: "cred-4",
    environmentId: "env-context7-default",
    ownerId: "u-admin",
    ownerEmail: "admin@example.com",
    scope: "personal",
    podId: "pod-context7-admin",
    secretStorage: "Database",
    createdAt: "2026-05-02T14:00:00Z",
  },
  {
    id: "cred-5",
    environmentId: "env-context7-default",
    ownerId: "u-alice",
    ownerEmail: "alice@example.com",
    scope: "personal",
    podId: "pod-context7-alice",
    secretStorage: "Database",
    createdAt: "2026-05-02T14:30:00Z",
  },
  {
    id: "cred-6",
    environmentId: "env-context7-default",
    ownerId: "u-bob",
    ownerEmail: "bob@example.com",
    scope: "personal",
    podId: "pod-context7-bob",
    secretStorage: "Database",
    createdAt: "2026-05-03T23:01:00Z",
  },
  {
    id: "cred-7",
    environmentId: "env-github-readonly",
    ownerId: "u-team-data",
    ownerEmail: "data-platform (team)",
    scope: "team",
    podId: "pod-github-readonly",
    secretStorage: "Vault",
    createdAt: "2026-04-25T09:00:00Z",
  },
  {
    id: "cred-8",
    environmentId: "env-github-admin",
    ownerId: "u-team-sre",
    ownerEmail: "sre (team)",
    scope: "team",
    podId: "pod-github-admin",
    secretStorage: "Vault",
    createdAt: "2026-04-25T09:05:00Z",
  },
  {
    id: "cred-9",
    environmentId: "env-jira-dev",
    ownerId: "u-admin",
    ownerEmail: "admin@example.com",
    scope: "personal",
    podId: "pod-jira-dev",
    secretStorage: "Database",
    createdAt: "2026-04-22T09:01:00Z",
  },
  {
    id: "cred-10",
    environmentId: "env-jira-dev",
    ownerId: "u-alice",
    ownerEmail: "alice@example.com",
    scope: "personal",
    podId: "pod-jira-dev",
    secretStorage: "Database",
    createdAt: "2026-04-23T11:00:00Z",
  },
  {
    id: "cred-11",
    environmentId: "env-jira-staging",
    ownerId: "u-team-data",
    ownerEmail: "data-platform (team)",
    scope: "team",
    podId: "pod-jira-staging",
    secretStorage: "Vault",
    createdAt: "2026-04-22T09:06:00Z",
  },
  {
    id: "cred-12",
    environmentId: "env-jira-production",
    ownerId: "u-team-sre",
    ownerEmail: "sre (team)",
    scope: "team",
    podId: "pod-jira-production",
    secretStorage: "Vault",
    createdAt: "2026-04-22T09:11:00Z",
  },
];

export const currentUser = {
  id: "u-admin",
  email: "admin@example.com",
  teamIds: ["team-studio1", "team-studio2", "team-data-platform", "team-sre"],
};
